name: fuzzy_chatbot
description: Simple fuzzy chatbot built with Pharaoh Dart & Google Generative AI
version: 1.0.0

environment:
  sdk: ^3.2.3

dependencies:
  pharaoh:

dev_dependencies:
  lints: ^2.1.0
  spookie:
